#!/usr/bin/env bash

execpath=`pwd`
cowpath="$execpath/tools/cow/"
cfgfile="~/.cow/rc"

david_setup(){
    echo "[DOING] checking cow path..."
    if [ ! -d $cowpath ]; then
        echo "[DOING] creating cow path..."
        mkdir -p $cowpath
    fi
    echo "[DOING] installing cow client..."
    cd $cowpath
    curl -L git.io/cow | bash
    cd execpath
    echo "[DOING] creating config file..."
    read -sp "password: " $password
    echo -e "/n"
    cat >> $cfgfile <<!EOF!
proxy = ss://aes-256-cfb:$password@107.170.234.24:8388
!EOF!
}

david_usage(){
    cat <<!EOF!
usage: $0 <command> [<option>]
command:
    setup       setup the vpn.
    on          starting the vpn.
    off         stopping the vpn.
    proxy       set proxy.

fq means go through the GFW.
!EOF!
}

case $1 in
    setup)
        echo "[DOING] creating configulation..."
        david_setup
        exit 0
        ;;
    on)
        echo "[DOING] connecting shadowsocks..."
        if [[ ! -f $cfgfile || ! -r $cfgfile ]]; then
            david_setup
        fi
        echo "[DOING] starting cow client..."
        $cowpath/cow &
        echo "[WARNING] cow is working."
        exit 0
        ;;
    off)
        exit 0
        ;;
    proxy)
        echo "[DOING] setting the proxy..."
        http_proxy="http://127.0.0.1:1080"
        export http_proxy
        exit 0
        ;;
    *)
        david_usage
        exit 3
        ;;
esac
