#!/usr/bin/env bash

cfgpath="tools/shadowsocks/"
cfgfile="$cfgpath/shadowsocks.cfg"

david_setup(){
    echo "[DOING] checking cfg path..."
    if [ ! -d $cfgpath ]; then
        echo "[DOING] creating cfg path..."
        mkdir $cfgpath
    fi
    echo "[DOING] installing shadowsocks client..."
    pip install shadowsocks
    yum install M2Crypto
    echo "[DOING] creating cfg file..."
    cat > $cfgfile <<!EOF!
{
    "server":"107.170.234.24",
    "server_port":8388,
    "local_port":1080,
    "password":"shadowsockspwd",
    "timeout":600,
    "method":"aes-256-cfb"
}
!EOF!
}

david_usage(){
    cat <<!EOF!
usage: $0 <command> [<option>]
command:
    setup       setup the vpn.
    on          starting the vpn.
    off         stopping the vpn.
    proxy       set proxy.

fq means go through the GFW.
!EOF!
}

case $1 in
    setup)
        echo "[DOING] creating configulation..."
        david_setup
        exit 0
        ;;
    on)
        echo "[DOING] connecting shadowsocks..."
        if [[ ! -f $cfgfile || ! -r $cfgfile ]]; then
            david_setup
        fi
        echo "[DOING] starting shadowsocks client..."
        sslocal -c $cfgfile
        echo "[WARNING] shadowsocks is working."
        exit 0
        ;;
    off)
        exit 0
        ;;
    proxy)
        echo "[DOING] setting the proxy..."
        http_proxy="http://127.0.0.1:1080"
        export http_proxy
        exit 0
        ;;
    *)
        david_usage
        exit 3
        ;;
esac
