#! /usr/bin/env bash

# david_inittool <name> <url>
david_inittool(){
    local name=$1
    local url=$2
    if [ -d ./tools/$name ]; then
        echo "[DOING] upgrading $name"
        if [[ -d ./tools/$name/.git && -w ./tools/$name/.git ]]; then
            cd ./tools/$name
            git pull
            cd ../../
        else
            echo "[ERROR] cannot find .git in $name."
        fi
    else
        echo "[DOING] downloading $name"
        git clone $url ./tools/$name
    fi
}

if [[ -d ./tools/ && -w ./tools/ ]]; then
    case $1 in
        chnroutes)
            echo "[DOING] initing $name"
            david_inittool "chnroutes" "https://github.com/fivesheep/chnroutes.git"
            echo "[DOING] installing models..."
            pip install argparse
            ;;
        *)
            ;;
    esac
fi
